### ISSUE TITLE
No CMAKE_C_COMPILER could be found

### ISSUE THREAD

**Issue by JACKHAHA363** [bdoin/GCompris-qt#116]
I am using OSx and after I tried to compile the project via Qt-creator and CMake. The following error appears:

The C/CXX compiler identification is unknown
at line 8 of CMakeLists.txt,
No CMAKE_C/CXX_COMPILER could be found

I am pretty sure I have both clang and clang++ installed.

**Comment by petitlapin** [comment]
Hi,
we strongly recommand to develop on a linux distribution if possible.

For your issue, have you tried to directly pass the compilers as arguments as in https://cmake.org/pipermail/cmake/2015-April/060360.html ?

Johnny

**Comment by bdoin** [comment]
As said, it is much easier to develop on GNU/Linux. It is too hard to provide support on MacOSX. There are some instructions in platforms/macosx/README.
