### ISSUE TITLE
Please differentiate between sv_FI and sv_SE

### ISSUE THREAD

**Issue by avtobiff** [bdoin/GCompris-qt#59]
Choosing `Svenska` as language in the settings renders the locale
`sv_FI.UTF-8` on my system. This is not my preferred locale, I prefer
`sv_SE.UTF-8`.

Either set the default Swedish language to use `sv_SE.UTF-8` or, better,
include both `sv_SE.UTF-8` and `sv_FI.UTF-8`.

**Comment by bdoin** [comment]
What is the difference between them?

**Comment by avtobiff** [comment]
On Fri, Feb 13, 2015 at 9:45 PM, Bruno Coudoin <notifications@github.com> wrote:
>
> What is the difference between them?

The obvious thing is that sv_FI a Finnish locale while sv_SE is a
Swedish locale. Consequences following are country names,
currency, telephone codes, and such things.

There are also differences in linguistics and vocabulary between
them. How much, I don't know exactly; but e.g. there are some slight
differences in how dates and time are represented.

As a comparison, GCompris differenciates between en_UK and
en_US.

**Comment by bdoin** [comment]
fixed in the master branch
